// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA7DuRv_OE5nqCVCTrkkfQSL6L3gKURE8',
    appId: '1:489332548768:web:2b427132817704e65595c5',
    messagingSenderId: '489332548768',
    projectId: 'fir-flutter-codelab-89a70',
    authDomain: 'fir-flutter-codelab-89a70.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-89a70.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxU7ggGDI9WpPPihp7cPcp7TuenWEXrzY',
    appId: '1:489332548768:android:ad56ac5d0c02006e5595c5',
    messagingSenderId: '489332548768',
    projectId: 'fir-flutter-codelab-89a70',
    storageBucket: 'fir-flutter-codelab-89a70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClXPYzKcP-POvUJsPgd0fbNmxa_sdwJ44',
    appId: '1:489332548768:ios:5c795bcff00ad9655595c5',
    messagingSenderId: '489332548768',
    projectId: 'fir-flutter-codelab-89a70',
    storageBucket: 'fir-flutter-codelab-89a70.firebasestorage.app',
    iosBundleId: 'com.whitewings.FirebaseMeetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClXPYzKcP-POvUJsPgd0fbNmxa_sdwJ44',
    appId: '1:489332548768:ios:5c795bcff00ad9655595c5',
    messagingSenderId: '489332548768',
    projectId: 'fir-flutter-codelab-89a70',
    storageBucket: 'fir-flutter-codelab-89a70.firebasestorage.app',
    iosBundleId: 'com.whitewings.FirebaseMeetup',
  );
}
